/**
 * Regenerates DESIGNS.md — the same gallery as /designs, but readable inside
 * GitHub. Run after adding a design (`bun run designs:md`); CI checks the
 * file is in sync.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { readDesigns, ROOT } from './designs-fs';

const SITE = 'https://tayles.co.uk';

const dateFormatter = new Intl.DateTimeFormat('en-GB', {
  timeZone: 'UTC',
  day: 'numeric',
  month: 'long',
  year: 'numeric',
});

const designs = readDesigns().toReversed();

const lines: string[] = [
  '# Designs',
  '',
  "<!-- Generated by `bun run designs:md`. Edit the design's",
  '     `src/designs/<slug>/index.md` instead of this file. -->',
  '',
  `[tayles.co.uk](${SITE}) wears a different design every week — a new one is`,
  'generated, screenshotted and merged automatically. Every design it has ever',
  'worn stays online at its own URL. Newest first.',
  '',
  `**${designs.length} design${designs.length === 1 ? '' : 's'}** ·`,
  `[Browse them live](${SITE}/designs)`,
  '',
];

for (const design of designs) {
  const dir = `src/designs/${design.slug}`;

  lines.push(
    '---',
    '',
    `## ${design.name}`,
    '',
    `${dateFormatter.format(design.date)} · \`${design.slug}\``,
    '',
    design.description,
    '',
  );

  if (design.hasScreenshot) {
    lines.push(`[![${design.name}](${dir}/screenshot.webp)](${dir}/)`, '');
  } else {
    lines.push('_No screenshot yet — run `bun run screenshots`._', '');
  }

  const tags = design.tags.map((tag) => `\`${tag}\``).join(' ');
  lines.push(
    `[Live](${SITE}/designs/${design.slug}) · [Source](${dir}/index.astro)` +
      (tags ? ` · ${tags}` : ''),
    '',
  );
}

writeFileSync(join(ROOT, 'DESIGNS.md'), `${lines.join('\n').trimEnd()}\n`);
console.log(`📝 DESIGNS.md — ${designs.length} designs`);
