import { glob } from 'astro/loaders';
import { z } from 'astro/zod';
import { defineCollection } from 'astro:content';

/**
 * Every design lives in its own directory under `src/designs/<slug>/`:
 *
 *   index.astro      the design itself
 *   index.md         this metadata, plus the screenshot embedded for GitHub
 *   screenshot.webp  generated by `bun run screenshots`
 *
 * The screenshot is deliberately *not* a frontmatter field — it is found by
 * filename convention, so a freshly generated design builds before it has
 * ever been photographed.
 */
const designs = defineCollection({
  loader: glob({
    pattern: '*/index.md',
    base: './src/designs',
    generateId: ({ entry }) => entry.split('/')[0] ?? entry,
  }),
  schema: z.object({
    name: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    tags: z.array(z.string()).default([]),
  }),
});

export const collections = { designs };
